

///////////////////////// LOCALHOST ///////////////////////////////

// get all contacts
###
GET http://localhost:8080/contacts

// get single contact by ID
// Example: Test
###
GET http://localhost:8080/contacts/696acbbb22a3cf17053b03a9

// Create new contact
###
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testing",
  "email": "test@example.com",
  "favoriteColor": "Test",
  "birthday": "1990-01-01"
}

// Update contact
// Example: Test
###
PUT http://localhost:8080/contacts/696acbbb22a3cf17053b03a9
Content-Type: application/json

{
  "firstName": "Lisiate",
  "lastName": "Ata",
  "email": "lisiate@example.com",
  "favoriteColor": "Purple",
  "birthday": "1984-15-02"
}

// Delete contact
// Example: Test
###
DELETE http://localhost:8080/contacts/69749bc7889e38a32ce307b8

///////////////////////////// RENDER ////////////////////////////////
// GET all contacts
###
GET https://cse341-week1-personal.onrender.com/contacts

// get single contact by ID
// Example: Lisiate
###
GET https://cse341-week1-personal.onrender.com/contacts/696acbbb22a3cf17053b03a9

// Create new contact
###
POST  https://cse341-week1-personal.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Testing",
  "email": "test@example.com",
  "favoriteColor": "Test",
  "birthday": "1901-01-01"
}

// Update contact
// Example: Test
###
PUT https://cse341-week1-personal.onrender.com/contacts/6974a4870de4fa502e553555
Content-Type: application/json

{
  "firstName": "Test Completed",
  "lastName": "Successful",
  "email": "test@example.com",
  "favoriteColor": "Test",
  "birthday": "1900-01-01"
}

// Delete contact
// Example: Test
###
DELETE https://cse341-week1-personal.onrender.com/contacts/6974a4870de4fa502e553555

